REM filepath: C:\Users\laxmi\OneDrive\Desktop\PBL2\setup.bat
@echo off
echo Setting up WebAssure Scanner...

echo Installing required Python packages...
pip install pymongo flask python-dotenv fpdf requests

echo Setting up fonts...
python setup_fonts.py

echo Starting the application...
python app.py